## Esercizi

1. Lettura della documentazione - Leggere la documentazione [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor) e di [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics) per poter eseguire quanto visto in questa lezione su GPU.
2. Crea un vettore casuale con dimensione `(5, 5)`.
3. Esegui una moltiplicazione tra matrici tra in tensore creato nel punto 2 con un'altro tensore di dimensione `(1, 5)` (attento alle dimensioni!).
4. Fissa il seed al numero `15` e ripeti i punti 2 e 3 diverse volte.
5. Inizializza la GPU e assicurati che stia funzionando
6. Crea due tensori casuali di dimensioni `(2, 4)` e caricale su GPU.
7. Esegui una moltiplicazione tra matrici tra i tensori creati nel punto 6.
8. Trova il massimo e il minimo dell'output del punto 7.
9. Trova gli indici del valore massimo e minimo dell'output del punto 7 (non abbiamo visto questo metodo, è il momento di verificare la vostra comprensione della documentazione!).
10. Crea un tensore casuale con shape `(1, 1, 1, 8)`, comprimilo rimuovendo tutte le dimensioni `1`, poi riportalo alla dimensione originale.

In [1]:
import torch
torch.__version__

'2.3.0+cu121'

2. Crea un vettore casuale con dimensione `(5, 5)`.

In [2]:
#Punto 2
t1 = torch.rand([5,5])
t1

tensor([[0.4913, 0.0700, 0.7951, 0.1160, 0.9025],
        [0.5237, 0.0268, 0.9181, 0.9029, 0.9833],
        [0.3981, 0.5739, 0.6503, 0.0229, 0.9522],
        [0.5216, 0.5291, 0.9670, 0.0922, 0.8917],
        [0.5733, 0.4543, 0.2415, 0.6571, 0.9218]])

In [3]:
t1.shape

torch.Size([5, 5])

3. Esegui una moltiplicazione tra matrici tra in tensore creato nel punto 2 con un'altro tensore di dimensione `(1, 5)` (attento alle dimensioni!).

In [4]:
t2 = torch.rand([1,5])
t2

tensor([[0.4482, 0.3804, 0.5275, 0.1605, 0.1160]])

In [5]:
t1.shape, t2.shape

(torch.Size([5, 5]), torch.Size([1, 5]))

In [6]:
t1.shape, t2.T.shape

(torch.Size([5, 5]), torch.Size([5, 1]))

In [7]:
t3 = t1 @ t2.T
t3

tensor([[0.7896],
        [0.9882],
        [0.8539],
        [1.0634],
        [0.7696]])

In [8]:
t3.shape

torch.Size([5, 1])

4. Fissa il seed al numero `15` e ripeti i punti 2 e 3 diverse volte.

In [9]:
#Punto 4
torch.manual_seed(15)
t1 = torch.rand([5,5])
t2 = torch.rand([1,5])
t3 = t1 @ t2.T
t3

tensor([[0.5523],
        [0.7028],
        [0.7011],
        [1.0323],
        [0.6487]])

5. Inizializza la GPU e assicurati che stia funzionando


In [10]:
#Punto 5
torch.cuda.is_available()

True

In [11]:
t3.device

device(type='cpu')

6. Crea due tensori casuali di dimensioni `(2, 4)` e caricale su GPU.


In [12]:
#Punto 6
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
device

device(type='cuda')

In [13]:
t4 = torch.rand([2,4]).to(device)
t5 = torch.rand([2,4]).to(device)
t5.device

device(type='cuda', index=0)

7. Esegui una moltiplicazione tra matrici tra i tensori creati nel punto 6.


In [14]:
#Punto 7
t6 = t4 @ t5.T
t6

tensor([[1.3524, 1.3537],
        [1.0139, 0.9029]], device='cuda:0')

8. Trova il massimo e il minimo dell'output del punto 7.


In [15]:
#Punto 8
max_t6 = t6.max()
max_t6

tensor(1.3537, device='cuda:0')

In [16]:
min_t6 = t6.min()
min_t6

tensor(0.9029, device='cuda:0')

9. Trova gli indici del valore massimo e minimo dell'output del punto 7 (non abbiamo visto questo metodo, è il momento di verificare la vostra comprensione della documentazione!).

In [17]:
#Punto 9
arg_min_t6 = t6.argmin()
arg_min_t6

tensor(3, device='cuda:0')

In [18]:
t6.flatten()

tensor([1.3524, 1.3537, 1.0139, 0.9029], device='cuda:0')

In [19]:
arg_max_t6 = t6.argmax()
arg_max_t6

tensor(1, device='cuda:0')

10. Crea un tensore casuale con shape `(1, 1, 1, 8)`, comprimilo rimuovendo tutte le dimensioni `1`, poi riportalo alla dimensione originale.

In [20]:
#Punto 10
t7 = torch.rand([1,1,1,8])
t7

tensor([[[[0.2095, 0.5280, 0.4871, 0.0597, 0.9298, 0.3724, 0.0183, 0.2798]]]])

In [21]:
t7.shape

torch.Size([1, 1, 1, 8])

In [22]:
t7_squeezed = t7.squeeze()
t7_squeezed

tensor([0.2095, 0.5280, 0.4871, 0.0597, 0.9298, 0.3724, 0.0183, 0.2798])

In [23]:
t7_squeezed.shape

torch.Size([8])

In [24]:
t7_reshaped = t7.reshape([1,1,1,8])
t7_reshaped

tensor([[[[0.2095, 0.5280, 0.4871, 0.0597, 0.9298, 0.3724, 0.0183, 0.2798]]]])

In [25]:
t7_reshaped.shape

torch.Size([1, 1, 1, 8])