## Operazioni sui Tensori

### Inizializzazione

In [1]:
import torch
torch.__version__

'2.3.0+cu121'

### Creazione di Tensori

I Tensori sono il componente chiave di PyTorch. Sul sito ufficiale si trova molta documentazione legata alla classe [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html).

Se non avete mai letto questa documentazione, vi invito a fermare il video e dedicare qualche minuto alla lettura di questa pagina.

> **Nota bene:** Il focus di questi esercizi pratici è la scrittura di codice. Tuttavia, gli esercizi richiedono spesso familiarità con delle classi e con la documentazione di PyTorch. In ogni parte del corso quindi, se vi sentite di non avere chiaro il funzionamento di qualcosa, fermate il video e provare a leggere in maniera approfondita la documentazione a riguardo.
Questo modo di lavorare vi accompagnerà probabilmente per la vostra intera esperienza professionale con PyTorch.

Ora possiamo iniziare a lavorare.

Il primo tensore che andiamo a vedere si chiama **scalare**.

Uno scalare è un numero singolo, possiamo anche definirlo un tensore a dimensione 0.

In [2]:
# Scalare
scalare = torch.tensor(4)
scalare

tensor(4)

Vediamo anche il tipo di questo tensore

In [3]:
type(scalare)

torch.Tensor

Possiamo vedere le dimensioni di un `torch.Tensor` usando l'attributo `ndim`.

In [4]:
scalare.ndim

0

Possiamo anche trasformarlo in un integer usando il metodo `item()`

In [5]:
integer = scalare.item()
integer

4

In [6]:
type(integer)

int

Possiamo passare ora al **vettore**.

Un vettore è un tensore monodimensionale, che può contenere diversi numeri

In [7]:
# Vettore
vettore = torch.tensor([4, 6, 8])
vettore

tensor([4, 6, 8])

Quante dimensioni pensate che abbia?

In [8]:
vettore.ndim

1

Qualcuno potrebbe aver dato la risposta sbagliata.

Un piccolo trucco:

Il numero di dimensioni di un tensore è dato da il numero di parentesi quadre aperte (`[`).

L'altro concetto importante è quello di **shape** di un tensore.

La shape fa riferimento a quanti elementi ci sono in ogni dimensione del tensore.


In [9]:
vettore.shape

torch.Size([3])

Vediamo ora una **matrice**

In [10]:
# Matrice
matrice = torch.tensor([[1, 7],
                       [15, 24]])
matrice

tensor([[ 1,  7],
        [15, 24]])

Provate a indovinare **ndim** e **shape**

In [11]:
matrice.ndim

2

In [12]:
matrice.shape

torch.Size([2, 2])

Ora che abbiamo capito, possiamo creare un **tensore** N-dimensionale

In [13]:
# Tensore
tensore = torch.tensor([[[1, 22, 13],
                        [78, 2, 15],
                        [7, 8, 12]]])
tensore

tensor([[[ 1, 22, 13],
         [78,  2, 15],
         [ 7,  8, 12]]])

Non è difficile capire la dimensione

In [14]:
tensore.ndim

3

La **shape** invece, richiede un po' di ragionamento.

Le posizioni nella shape, fanno riferimento alla dimensione dalla più esterna alla più interna

In [15]:
tensore.shape

torch.Size([1, 3, 3])

Vediamo se è tutto chiaro

In [16]:
tensore2 = torch.tensor([[[1,6],
                          [78,90],
                          [11,32],
                          [16,15]],
                         [[67,12],
                          [5,7],
                          [1,14],
                          [5,2]],
                         [[6,1],
                          [8,12],
                          [54,66],
                          [11,32]]])
tensore2

tensor([[[ 1,  6],
         [78, 90],
         [11, 32],
         [16, 15]],

        [[67, 12],
         [ 5,  7],
         [ 1, 14],
         [ 5,  2]],

        [[ 6,  1],
         [ 8, 12],
         [54, 66],
         [11, 32]]])

In [17]:
tensore2.shape

torch.Size([3, 4, 2])

Un breve Recap.

| Nome | Cosa rappresenta | Dimensioni |
| ----- | ----- | ----- |
| **scalare** | numero singolo | 0 |
| **vettore** | array di numeri | 1 |
| **matrice** | array di numeri in 2 dimensioni | 2 |
| **tensore** | array di numeri n-dimensionale | N |

### Tensori precompilati

Fino ad ora abbiamo creato tensori e li abbiamo riempiti manualmente.
Tuttavia, spesso andremo a creare tensori riempiti automaticamente in un certo modo usando come input la loro dimensione.

Iniziamo con dei tensori riempiti casualmente

In [18]:
# Tensore casuale (3, 4)
casuale = torch.rand(size=(3, 4))
casuale

tensor([[0.9521, 0.3887, 0.9971, 0.6179],
        [0.4328, 0.2063, 0.3073, 0.7381],
        [0.8549, 0.7308, 0.8011, 0.1152]])

Il parametro size può essere modificato arbitrariamente

In [19]:
casuale = torch.rand(size=(1, 3, 4, 2))
casuale

tensor([[[[0.3054, 0.4751],
          [0.9015, 0.7209],
          [0.9474, 0.3019],
          [0.0649, 0.4736]],

         [[0.5365, 0.3458],
          [0.3239, 0.1274],
          [0.8423, 0.2994],
          [0.6008, 0.2162]],

         [[0.5484, 0.3234],
          [0.0682, 0.7535],
          [0.1693, 0.0235],
          [0.3407, 0.0449]]]])

In [20]:
casuale.ndim, casuale.shape

(4, torch.Size([1, 3, 4, 2]))

Possiamo anche creare tensori con solo 0 o solo 1

In [21]:
# Crea un tensore di soli zeri
zeri = torch.zeros(size=(3, 4))
zeri

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
# Crea un tensore di soli uni
uni = torch.ones(size=(3, 4))
uni

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

Allo stesso modo, possiamo anche creare matrici identità (possibile solo con matrici quadrate)

In [23]:
# Crea una matrice identità
identita = torch.eye(3)
identita

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

### Range e Tensor-like

Possiamo creare Tensori usando range di numeri e creare tensori di un certo tipo richiamando un altro tipo di tensore

In [24]:
# Range tra 0 e 10
zero_a_dieci = torch.arange(start=0, end=10, step=1)
zero_a_dieci

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
# Vettore di zeri della stessa dimensione
dieci_zeri = torch.zeros_like(input=zero_a_dieci)
dieci_zeri

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

Ci sono [diversi tipi di Tensori in PyTorch](https://pytorch.org/docs/stable/tensors.html#data-types).

Alcuni si riferiscono a tensori su CPU, altri su GPU.

Quando il tipo di tensore contiene `torch.cuda` anywhere, è solitamente un tensore su GPU.

Il tipo di default è `torch.float32` oppure `torch.float`.

Viene anche chiamato "32-bit floating point".

Esistono anche 16-bit floating point (`torch.float16` o `torch.half`) e 64-bit floating point (`torch.float64` o `torch.double`).

Oltro a questi ci sono 8-bit, 16-bit, 32-bit e 64-bit integers.

E altri..

Tutti questi tipi servono per avere diverse precisioni nella computazione.

Minor precisione significa meno spazio occupato, maggiore velocità, ma peggiore risultati.

Qui potete trovare la [documentazione PyTorch documentation con i tipi di Tensore](https://pytorch.org/docs/stable/tensors.html#data-types).

Per creare tensori con un tipo specifico, possiamo usare il parametro `dtype`.

Possiamo inoltre specificare se si trovano su CPU o GPU con il parametri `device` e se vogliamo che le operazioni sul tensore vengano registrate per il calcolo di gradienti (ad esempio durante il training) con il parametro `requires_grad`


In [26]:

float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16,
                               device=None, # default
                               requires_grad=False)

float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

Una volta creato un tensore, possiamo accedere alle sue informazioni riguardo a device e typo, allo stesso modo il cui lo facevamo per shape e ndim

In [27]:
# Informazioni
print(float_16_tensor)
print(f"Dimensioni del tensore: {float_16_tensor.ndim}")
print(f"Shape del tensore: {float_16_tensor.shape}")
print(f"Datatype del tensore: {float_16_tensor.dtype}")
print(f"Device dove si trova il tensore: {float_16_tensor.device}")

tensor([3., 6., 9.], dtype=torch.float16)
Dimensioni del tensore: 1
Shape del tensore: torch.Size([3])
Datatype del tensore: torch.float16
Device dove si trova il tensore: cpu


### Manipolare i Tensori

Possiamo fare diverse operazioni con i tensori:
* Addizioni
* Sottrazioni
* Moltiplicazioni (element-wise)
* Divisioni
* Moltiplicazione tra matrici

Iniziamo con le operazioni basilari: addizione (`+`), sottrazione (`-`), moltiplicazione (`*`).


In [28]:
tensore = torch.tensor([4, 5, 6])
tensore + 20

tensor([24, 25, 26])

In [29]:
tensore - 2

tensor([2, 3, 4])

In [30]:
tensore * 10

tensor([40, 50, 60])

In PyTorch esistono anche delle funzioni built-in come [`torch.mul()`](https://pytorch.org/docs/stable/generated/torch.mul.html#torch.mul) e [`torch.add()`](https://pytorch.org/docs/stable/generated/torch.add.html) per queste operazioni.

In [31]:
torch.add(tensore, 20)

tensor([24, 25, 26])

In [32]:
torch.add(tensore, -2)

tensor([2, 3, 4])

In [33]:
torch.mul(tensore, 10)

tensor([40, 50, 60])

Possiamo utilizzare anche queste funzioni come metodi del tensore

In [34]:
tensore.add(20)

tensor([24, 25, 26])

In [35]:
tensore.add(-2)

tensor([2, 3, 4])

In [36]:
tensore.mul(10)

tensor([40, 50, 60])

Se abbiamo due tensori `*` e `torch.mul()` eseguiranno la moltiplicazione element-wise

In [37]:
tensore, tensore * tensore, torch.mul(tensore, tensore), tensore.mul(tensore)

(tensor([4, 5, 6]),
 tensor([16, 25, 36]),
 tensor([16, 25, 36]),
 tensor([16, 25, 36]))

Moltiplicazione tra matrici


PyTorch implementa questa funzione nel metodo [`torch.matmul()`](https://pytorch.org/docs/stable/generated/torch.matmul.html).
In alternative, possiamo usare il simbolo `@`.

Dobbiamo ricordare qualche regola:

1. Le **dimensioni interne** devono essere equivalenti:
  * `(3, 2) @ (3, 2)` non funziona
  * `(2, 3) @ (3, 2)` funziona
  * `(3, 2) @ (2, 3)` funziona
2. Il risultato ha la shape delle **dimensioni esterne**:
 * `(2, 3) @ (3, 2)` -> `(2, 2)`
 * `(3, 2) @ (2, 3)` -> `(3, 3)`

Se chiamamiamo `torch.matmul()` su un vettore, eseguirà il prodotto scalare.


In [38]:
tensore = torch.tensor([1, 2, 3])
tensore.shape

torch.Size([3])

In [39]:
# Element-wise
tensore * tensore

tensor([1, 4, 9])

In [40]:
# Prodotto scalare
torch.matmul(tensore, tensore)

tensor(14)

In [41]:
tensore @ tensore

tensor(14)

| Operazione | Calcolo | Simbolo | Funzione |
| ----- | ----- | ----- | ----- |
| **Moltiplicazione element-wise** | `[1*1, 2*2, 3*3]` = `[1, 4, 9]` | `tensore * tensore` | `tensore.mul(tensor)` |
| **Moltiplicazione tra matrici** | `[1*1 + 2*2 + 3*3]` = `[14]` | `tensore @ tensore` | `tensore.matmul(tensore)` |

In [42]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)

#torch.matmul(tensor_A, tensor_B)  darebbe errore, le dimensioni non vanno bene


In [43]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [44]:
#Trasposizione
tensor_B.T, tensor_B.T.shape

(tensor([[ 7.,  8.,  9.],
         [10., 11., 12.]]),
 torch.Size([2, 3]))

In [45]:
tensor_A @ tensor_B.T

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

### Aggregazioni

Vediamo alcuni metodi per aggregare i tensori.

In [46]:
x = torch.arange(0, 100, 10)

In [48]:
print(f"Minimo: {x.min()}")
print(f"Massimo: {x.max()}")
print(f"Somma: {x.sum()}")

Minimo: 0
Massimo: 90
Somma: 450


Per trovare la media, serve che il tensore sia di tipo `torch.float32`

In [49]:
# print(f"Media: {x.mean()}") # genera un errore
print(f"Media: {x.type(torch.float32).mean()}")

Media: 45.0


Lo stesso si può fare con i metodi di `torch`.

In [50]:
torch.max(x), torch.min(x), torch.mean(x.type(torch.float32)), torch.sum(x)

(tensor(90), tensor(0), tensor(45.), tensor(450))

### Rimodellare i tensori

Ci sono diversi metodi per modificare le dimensioni di un tensore senza cambiare i valori al suo interno.

| Metodo | Descrizione |
| ----- | ----- |
| [`torch.reshape(input, shape)`](https://pytorch.org/docs/stable/generated/torch.reshape.html#torch.reshape) | Rimodella `input` in `shape` (se possibile) |
| [`torch.stack(tensors, dim=0)`](https://pytorch.org/docs/1.9.1/generated/torch.stack.html) | Concatena una sequenza di `tensori` su una nuova dimensione (`dim`), tutti i `tensori` devono avere la stessa dimensione. |
| [`torch.squeeze(input)`](https://pytorch.org/docs/stable/generated/torch.squeeze.html) | Compatta `input` per rimuovere tutte le dimensioni con valore `1`. |
| [`torch.unsqueeze(input, dim)`](https://pytorch.org/docs/1.9.1/generated/torch.unsqueeze.html) | Restituisce `input` con una nuova dimensione di valore `1` aggiunta a `dim`. |

Ce ne sono anche altre che potete trovare nella documentazione.

In [51]:
x = torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [52]:
#Questo tipo di reshape aggiunge una dimensione esterna
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [53]:
# Concatena tensori
x_stack = torch.stack([x, x, x, x], dim=0)
x_stack

tensor([[1., 2., 3., 4., 5., 6., 7.],
        [1., 2., 3., 4., 5., 6., 7.],
        [1., 2., 3., 4., 5., 6., 7.],
        [1., 2., 3., 4., 5., 6., 7.]])

In [54]:
print(f"Tensore con dimensione aggiunta: {x_reshaped}")
print(f"Shape: {x_reshaped.shape}")

# Rimuovi la dimensione aggiunta
x_squeezed = x_reshaped.squeeze()
print(f"\nNuovo tensore: {x_squeezed}")
print(f"Shape: {x_squeezed.shape}")

Tensore con dimensione aggiunta: tensor([[1., 2., 3., 4., 5., 6., 7.]])
Shape: torch.Size([1, 7])

Nuovo tensore: tensor([1., 2., 3., 4., 5., 6., 7.])
Shape: torch.Size([7])


In [55]:
#Processo inverso
print(f"Tensore squeezed: {x_squeezed}")
print(f"Shape: {x_squeezed.shape}")

## Aggiungiamo una dimensione extra
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNuovo tensore: {x_unsqueezed}")
print(f"Shape: {x_unsqueezed.shape}")

Tensore squeezed: tensor([1., 2., 3., 4., 5., 6., 7.])
Shape: torch.Size([7])

Nuovo tensore: tensor([[1., 2., 3., 4., 5., 6., 7.]])
Shape: torch.Size([1, 7])


### Selezionare dati dai tensori

Vogliamo poter accedere a una parte specifica dei dati del tensore.
Per questo è importante imparare a utilizzare gli indici.

Gli indici funzionano in maniera simile a quelli di `numpy`.

In [56]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

L'indicizzazione va dalla dimensione più esterna a quella più interna

In [58]:
print(f"Esterna:\n{x[0]}, {x[0].shape}")
print(f"Intermedia: {x[0][0]}, {x[0][0].shape}")
print(f"Interna: {x[0][0][0]}, , {x[0][0][0].shape}")

Esterna:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]), torch.Size([3, 3])
Intermedia: tensor([1, 2, 3]), torch.Size([3])
Interna: 1, , torch.Size([])


Possiamo utilizzare `:` per specificare "tutti i valori in una dimensione".

In [59]:
# Tutti i valori della dimensione 0 e l'indice 0 della dimensione 1
x[:, 0]

tensor([[1, 2, 3]])

In [60]:
#Tutti i valori delle dimensioni 0 e 1 ma solo l'indice 1 della dimensione 2
x[:, :, 1]

tensor([[2, 5, 8]])

In [61]:
# Tutti i valori della dimensione 0 ma solo l'indice 1 della dimensione 1 e 2
x[:, 1, 1]

tensor([5])